name: adaptive_design_widgets
description: A new Flutter package project.
version: 0.0.1
homepage: "https://github.com/BoseVJeff/adaptive_design_widgets/tree/new_start"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.6.3
  fluent_ui: ^4.4.1
  fluentui_system_icons: ^1.1.198
  flutter_adaptive_scaffold: ^0.1.2
  font_awesome_flutter: ^10.4.0
  macos_ui: ^1.12.2
  yaru: ^0.7.0
  yaru_icons: ^1.0.4
  yaru_widgets: ^2.3.1
  material_color_utilities: ^0.2.0
  material_symbols_icons: ^4.2663.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

  fonts:
    # Weights mapped according to https://stackoverflow.com/a/10909252
    # Regular Apple fonts
    # Fonts taken from https://developer.apple.com/fonts/
    - family: SF Pro
      fonts:
        - asset: fonts/SF-Pro/SF-Pro.ttf
          style: normal
        - asset: fonts/SF-Pro/SF-Pro-Italic.ttf
          style: italic
    - family: SF Compact
      fonts:
        - asset: fonts/SF-Compact/SF-Compact.ttf
          style: normal
        - asset: fonts/SF-Compact/SF-Comapct-Italic.ttf
          style: italic
    - family: SF Mono
      fonts:
        - asset: fonts/SF-Mono/SF-Mono-Light.otf
          style: normal
          weight: 300
        - asset: fonts/SF-Mono/SF-Mono-LightItalic.otf
          style: italic
          weight: 300
        - asset: fonts/SF-Mono/SF-Mono-Regular.otf
          style: normal
          weight: 400
        - asset: fonts/SF-Mono/SF-Mono-RegularItalic.otf
          style: italic
          weight: 400
        - asset: fonts/SF-Mono/SF-Mono-Medium.otf
          style: normal
          weight: 500
        - asset: fonts/SF-Mono/SF-Mono-MediumItalic.otf
          style: italic
          weight: 500
        - asset: fonts/SF-Mono/SF-Mono-Semibold.otf
          style: normal
          weight: 600
        - asset: fonts/SF-Mono/SF-Mono-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: fonts/SF-Mono/SF-Mono-Bold.otf
          style: normal
          weight: 700
        - asset: fonts/SF-Mono/SF-Mono-BoldItalic.otf
          style: italic
          weight: 700
        - asset: fonts/SF-Mono/SF-Mono-Heavy.otf
          style: normal
          weight: 900
        - asset: fonts/SF-Mono/SF-Mono-HeavyItalic.otf
          style: italic
          weight: 900
    - family: Roboto
    # Font and font weights taken from https://fonts.google.com/specimen/Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          style: normal
          weight: 900
        - asset: fonts/Roboto/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
    # Microsoft fonts
    # Taken from https://learn.microsoft.com/en-us/windows/apps/design/downloads/#fonts
    - family: Segoe-UI-VF
      fonts:
        - asset: fonts/Segoe-UI-VF/SegoeUI-VF.ttf